services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}   # MongoDB Atlas URI from your env

  frontend:
    build: ./fronted
    ports:
      - "80:80"
